// generated by goxsd; DO NOT EDIT

package ncbisubmission

import "time"

// Submission is generated from an XSD element.
type Submission struct {
	SchemaVersion string      `xml:"schema_version,omitempty,attr"`
	ResubmitOf    string      `xml:"resubmit_of,omitempty,attr"`
	Submitted     time.Time   `xml:"submitted,omitempty,attr"`
	LastUpdate    time.Time   `xml:"last_update,omitempty,attr"`
	Status        string      `xml:"status,omitempty,attr"`
	SubmissionID  string      `xml:"submission_id,attr"`
	Description   Description `xml:"Description"`
	Action        []Action    `xml:"Action"`
}

// Description is generated from an XSD element.
type Description struct {
	Comment            *string             `xml:"Comment,omitempty"`
	Submitter          *Submitter          `xml:"Submitter,omitempty"`
	Organization       []Organization      `xml:"Organization"`
	Hold               *Hold               `xml:"Hold,omitempty"`
	SubmissionSoftware *SubmissionSoftware `xml:"SubmissionSoftware,omitempty"`
}

// Submitter is generated from an XSD element.
type Submitter struct {
	AccountID string   `xml:"account_id,omitempty,attr"`
	UserName  string   `xml:"user_name,omitempty,attr"`
	Authority string   `xml:"authority,omitempty,attr"`
	Contact   *Contact `xml:"Contact,omitempty"`
}

// Contact is generated from an XSD element.
type Contact struct {
	Email    string   `xml:"email,attr"`
	SecEmail string   `xml:"sec_email,omitempty,attr"`
	Phone    string   `xml:"phone,attr"`
	Fax      string   `xml:"fax,attr"`
	Address  *Address `xml:"Address,omitempty"`
	Name     *Name    `xml:"Name,omitempty"`
}

// Address is generated from an XSD element.
type Address struct {
	PostalCode  string  `xml:"postal_code,omitempty,attr"`
	Department  *string `xml:"Department,omitempty"`
	Institution *string `xml:"Institution,omitempty"`
	Street      *string `xml:"Street,omitempty"`
	City        string  `xml:"City"`
	Sub         *string `xml:"Sub,omitempty"`
	Country     string  `xml:"Country"`
}

// Name is generated from an XSD element.
type Name struct {
	First  *string `xml:"First,omitempty"`
	Last   string  `xml:"Last"`
	Middle *string `xml:"Middle,omitempty"`
	Suffix *string `xml:"Suffix,omitempty"`
}

// Organization is generated from an XSD element.
type Organization struct {
	Type    string    `xml:"type,attr"`
	Role    string    `xml:"role,omitempty,attr"`
	OrgID   uint      `xml:"org_id,omitempty,attr"`
	URL     string    `xml:"url,omitempty,attr"`
	GroupID string    `xml:"group_id,omitempty,attr"`
	Name    Name      `xml:"Name"`
	Address *Address  `xml:"Address,omitempty"`
	Contact []Contact `xml:"Contact,omitempty"`
}

// Hold is generated from an XSD element.
type Hold struct {
	ReleaseDate time.Time `xml:"release_date,attr"`
}

// SubmissionSoftware is generated from an XSD element.
type SubmissionSoftware struct {
	Version string `xml:"version,omitempty,attr"`
}

// Action is generated from an XSD element.
type Action struct {
	ActionID            string `xml:"action_id,attr"`
	SubmitterTrackingID string `xml:"submitter_tracking_id,attr"`
}
