// generated by goxsd; DO NOT EDIT

package mvk14201912

import "time"

// СписокРешений is generated from an XSD element.
type СписокРешений struct {
	ВерсияФормата           string                   `xml:"ВерсияФормата"`
	ДатаСписка              time.Time                `xml:"ДатаСписка"`
	ДатаПредыдущегоСписка   *time.Time               `xml:"ДатаПредыдущегоСписка,omitempty"`
	СписокАктуальныхРешений СписокАктуальныхРешений  `xml:"СписокАктуальныхРешений"`
	СписокОтмененныхРешений *СписокОтмененныхРешений `xml:"СписокОтмененныхРешений,omitempty"`
}

// СписокАктуальныхРешений is generated from an XSD element.
type СписокАктуальныхРешений struct {
	Решение []Решение `xml:"Решение"`
}

// Решение is generated from an XSD element.
type Решение struct {
	ТипРешения      ТипРешения       `xml:"ТипРешения"`
	НомерРешения    string           `xml:"НомерРешения"`
	ДатаРешения     time.Time        `xml:"ДатаРешения"`
	Орган           string           `xml:"Орган"`
	ВидРешения      ВидРешения       `xml:"ВидРешения"`
	СписокСубъектов *СписокСубъектов `xml:"СписокСубъектов,omitempty"`
}

// ТипРешения is generated from an XSD element.
type ТипРешения struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// ВидРешения is generated from an XSD element.
type ВидРешения struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// СписокСубъектов is generated from an XSD element.
type СписокСубъектов struct {
	Субъект []Субъект `xml:"Субъект,omitempty"`
}

// Субъект is generated from an XSD element.
type Субъект struct {
	ИдСубъекта        string         `xml:"ИдСубъекта"`
	ТипСубъекта       ТипСубъекта    `xml:"ТипСубъекта"`
	СписокАдресов     *СписокАдресов `xml:"СписокАдресов,omitempty"`
	РешениеПоСубъекту *string        `xml:"РешениеПоСубъекту,omitempty"`
	Примечание        *string        `xml:"Примечание,omitempty"`
}

// ТипСубъекта is generated from an XSD element.
type ТипСубъекта struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// СписокАдресов is generated from an XSD element.
type СписокАдресов struct {
	Адрес []Адрес `xml:"Адрес"`
}

// Адрес is generated from an XSD element.
type Адрес struct {
	НормАдрес            *НормАдрес `xml:"НормАдрес,omitempty"`
	ТипАдреса            ТипАдреса  `xml:"ТипАдреса"`
	ТекстАдреса          string     `xml:"ТекстАдреса"`
	ИдентификаторФИАС    *string    `xml:"ИдентификаторФИАС,omitempty"`
	УровеньАдреснОбъекта *int       `xml:"УровеньАдреснОбъекта,omitempty"`
	Страна               *Страна    `xml:"Страна,omitempty"`
	Индекс               *string    `xml:"Индекс,omitempty"`
	ОКАТО                *string    `xml:"ОКАТО,omitempty"`
	Регион               *string    `xml:"Регион,omitempty"`
	АвтономныйОкруг      *string    `xml:"АвтономныйОкруг,omitempty"`
	Район                *string    `xml:"Район,omitempty"`
	Город                *string    `xml:"Город,omitempty"`
	ВнутригородскРайон   *string    `xml:"ВнутригородскРайон,omitempty"`
	НаселПункт           *string    `xml:"НаселПункт,omitempty"`
	Улица                *string    `xml:"Улица,omitempty"`
	Дом                  *string    `xml:"Дом,omitempty"`
	Корпус               *string    `xml:"Корпус,omitempty"`
	Строение             *string    `xml:"Строение,omitempty"`
	Помещение            *string    `xml:"Помещение,omitempty"`
}

// НормАдрес is generated from an XSD element.
type НормАдрес struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// ТипАдреса is generated from an XSD element.
type ТипАдреса struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// Страна is generated from an XSD element.
type Страна struct {
	Наименование string  `xml:"Наименование"`
	Код          *string `xml:"Код,omitempty"`
}

// СписокОтмененныхРешений is generated from an XSD element.
type СписокОтмененныхРешений struct {
	ОтмененноеРешение []ОтмененноеРешение `xml:"ОтмененноеРешение,omitempty"`
}

// ОтмененноеРешение is generated from an XSD element.
type ОтмененноеРешение struct {
	ТипРешения      ТипРешения       `xml:"ТипРешения"`
	НомерРешения    string           `xml:"НомерРешения"`
	ДатаРешения     time.Time        `xml:"ДатаРешения"`
	Орган           string           `xml:"Орган"`
	ВидРешения      ВидРешения       `xml:"ВидРешения"`
	СписокСубъектов *СписокСубъектов `xml:"СписокСубъектов,omitempty"`
}
