// generated by goxsd; DO NOT EDIT

package mvk14201912

import "time"

type (
	DateTimeXSDType time.Time
	DateXSDType     time.Time
	TimeXSDType     time.Time
)

// СписокРешений is generated from an XSD element.
type СписокРешений struct {
	ВерсияФормата           string                      `xml:"ВерсияФормата"`
	ДатаСписка              DateXSDType                 `xml:"ДатаСписка"`
	ДатаПредыдущегоСписка   *DateXSDType                `xml:"ДатаПредыдущегоСписка,omitempty"`
	СписокАктуальныхРешений СписокАктуальныхРешенийТип  `xml:"СписокАктуальныхРешений"`
	СписокОтмененныхРешений *СписокОтмененныхРешенийТип `xml:"СписокОтмененныхРешений,omitempty"`
}

// СписокАктуальныхРешенийТип is generated from an XSD element.
type СписокАктуальныхРешенийТип struct {
	Решение []РешениеТип `xml:"Решение"`
}

// РешениеТип is generated from an XSD element.
type РешениеТип struct {
	ТипРешения      СправочникТип       `xml:"ТипРешения"`
	НомерРешения    string              `xml:"НомерРешения"`
	ДатаРешения     DateXSDType         `xml:"ДатаРешения"`
	Орган           string              `xml:"Орган"`
	ВидРешения      СправочникТип       `xml:"ВидРешения"`
	СписокСубъектов *СписокСубъектовТип `xml:"СписокСубъектов,omitempty"`
}

// СправочникТип is generated from an XSD element.
type СправочникТип struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// СписокСубъектовТип is generated from an XSD element.
type СписокСубъектовТип struct {
	Субъект []СубъектТип `xml:"Субъект,omitempty"`
}

// СубъектТип is generated from an XSD element.
type СубъектТип struct {
	ИдСубъекта        string            `xml:"ИдСубъекта"`
	ТипСубъекта       СправочникТип     `xml:"ТипСубъекта"`
	СписокАдресов     *СписокАдресовТип `xml:"СписокАдресов,omitempty"`
	РешениеПоСубъекту *string           `xml:"РешениеПоСубъекту,omitempty"`
	Примечание        *string           `xml:"Примечание,omitempty"`
	ФЛ                *ФЛТип            `xml:"ФЛ,omitempty"`
	ЮЛ                *ЮЛТип            `xml:"ЮЛ,omitempty"`
}

// СписокАдресовТип is generated from an XSD element.
type СписокАдресовТип struct {
	Адрес []АдресТип `xml:"Адрес"`
}

// АдресТип is generated from an XSD element.
type АдресТип struct {
	НормАдрес            *СправочникТип `xml:"НормАдрес,omitempty"`
	ТипАдреса            СправочникТип  `xml:"ТипАдреса"`
	ТекстАдреса          string         `xml:"ТекстАдреса"`
	ИдентификаторФИАС    *string        `xml:"ИдентификаторФИАС,omitempty"`
	УровеньАдреснОбъекта *int           `xml:"УровеньАдреснОбъекта,omitempty"`
	Страна               *СтранаТип     `xml:"Страна,omitempty"`
	Индекс               *string        `xml:"Индекс,omitempty"`
	ОКАТО                *string        `xml:"ОКАТО,omitempty"`
	Регион               *string        `xml:"Регион,omitempty"`
	АвтономныйОкруг      *string        `xml:"АвтономныйОкруг,omitempty"`
	Район                *string        `xml:"Район,omitempty"`
	Город                *string        `xml:"Город,omitempty"`
	ВнутригородскРайон   *string        `xml:"ВнутригородскРайон,omitempty"`
	НаселПункт           *string        `xml:"НаселПункт,omitempty"`
	Улица                *string        `xml:"Улица,omitempty"`
	Дом                  *string        `xml:"Дом,omitempty"`
	Корпус               *string        `xml:"Корпус,omitempty"`
	Строение             *string        `xml:"Строение,omitempty"`
	Помещение            *string        `xml:"Помещение,omitempty"`
}

// СтранаТип is generated from an XSD element.
type СтранаТип struct {
	Наименование string  `xml:"Наименование"`
	Код          *string `xml:"Код,omitempty"`
}

// ФЛТип is generated from an XSD element.
type ФЛТип struct {
	ФИО                  string                     `xml:"ФИО"`
	Фамилия              *string                    `xml:"Фамилия,omitempty"`
	Имя                  *string                    `xml:"Имя,omitempty"`
	Отчество             *string                    `xml:"Отчество,omitempty"`
	ФИОЛат               *string                    `xml:"ФИОЛат,omitempty"`
	ДатаРождения         *DateXSDType               `xml:"ДатаРождения,omitempty"`
	ГодРождения          *string                    `xml:"ГодРождения,omitempty"`
	МестоРождения        *string                    `xml:"МестоРождения,omitempty"`
	ИНН                  *string                    `xml:"ИНН,omitempty"`
	СНИЛС                *string                    `xml:"СНИЛС,omitempty"`
	СписокДокументов     *СписокДокументовТип       `xml:"СписокДокументов,omitempty"`
	СписокДрНаименований *СписокДрНаименованийФЛТип `xml:"СписокДрНаименований,omitempty"`
}

// СписокДокументовТип is generated from an XSD element.
type СписокДокументовТип struct {
	Документ []ДокументТип `xml:"Документ,omitempty"`
}

// ДокументТип is generated from an XSD element.
type ДокументТип struct {
	ТипДокумента            СправочникТип `xml:"ТипДокумента"`
	Серия                   *string       `xml:"Серия,omitempty"`
	Номер                   *string       `xml:"Номер,omitempty"`
	ОрганВыдачи             *string       `xml:"ОрганВыдачи,omitempty"`
	ДатаВыдачи              *DateXSDType  `xml:"ДатаВыдачи,omitempty"`
	ДатаС                   *DateXSDType  `xml:"ДатаС,omitempty"`
	ДатаПо                  *DateXSDType  `xml:"ДатаПо,omitempty"`
	ПризнакДействительности *bool         `xml:"ПризнакДействительности,omitempty"`
}

// СписокДрНаименованийФЛТип is generated from an XSD element.
type СписокДрНаименованийФЛТип struct {
	ДрНаименование []ДрНаименованиеФЛТип `xml:"ДрНаименование,omitempty"`
}

// ДрНаименованиеФЛТип is generated from an XSD element.
type ДрНаименованиеФЛТип struct{}

// ЮЛТип is generated from an XSD element.
type ЮЛТип struct {
	НаименованиеЛат      *string                    `xml:"НаименованиеЛат,omitempty"`
	ДатаРегистрации      *DateXSDType               `xml:"ДатаРегистрации,omitempty"`
	МестоРегистрации     *string                    `xml:"МестоРегистрации,omitempty"`
	ОГРН                 *string                    `xml:"ОГРН,omitempty"`
	СписокДрНаименований *СписокДрНаименованийЮЛТип `xml:"СписокДрНаименований,omitempty"`
}

// СписокДрНаименованийЮЛТип is generated from an XSD element.
type СписокДрНаименованийЮЛТип struct {
	ДрНаименование []ДрНаименованиеЮЛТип `xml:"ДрНаименование"`
}

// ДрНаименованиеЮЛТип is generated from an XSD element.
type ДрНаименованиеЮЛТип struct{}

// СписокОтмененныхРешенийТип is generated from an XSD element.
type СписокОтмененныхРешенийТип struct {
	ОтмененноеРешение []РешениеТип `xml:"ОтмененноеРешение,omitempty"`
}
