// generated by goxsd; DO NOT EDIT

package omu10

import "time"

// СписокОМУ is generated from an XSD element.
type СписокОМУ struct {
	ВерсияФормата         string           `xml:"ВерсияФормата"`
	ДатаСписка            time.Time        `xml:"ДатаСписка"`
	ДатаПредыдущегоСписка *time.Time       `xml:"ДатаПредыдущегоСписка,omitempty"`
	АктуальныйСписок      АктуальныйСписок `xml:"АктуальныйСписок"`
}

// АктуальныйСписок is generated from an XSD element.
type АктуальныйСписок struct {
	Субъект []Субъект `xml:"Субъект"`
}

// Субъект is generated from an XSD element.
type Субъект struct {
	ИдСубъекта    int            `xml:"ИдСубъекта"`
	УНС           *string        `xml:"УНС,omitempty"`
	ТипСубъекта   ТипСубъекта    `xml:"ТипСубъекта"`
	История       История        `xml:"История"`
	СписокАдресов *СписокАдресов `xml:"СписокАдресов,omitempty"`
	Страна        *Страна        `xml:"Страна,omitempty"`
	Примечание    *string        `xml:"Примечание,omitempty"`
}

// ТипСубъекта is generated from an XSD element.
type ТипСубъекта struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// История is generated from an XSD element.
type История struct{}

// СписокАдресов is generated from an XSD element.
type СписокАдресов struct {
	Адрес []Адрес `xml:"Адрес"`
}

// Адрес is generated from an XSD element.
type Адрес struct {
	НормАдрес            *НормАдрес `xml:"НормАдрес,omitempty"`
	ТипАдреса            ТипАдреса  `xml:"ТипАдреса"`
	ТекстАдреса          string     `xml:"ТекстАдреса"`
	ИдентификаторФИАС    *string    `xml:"ИдентификаторФИАС,omitempty"`
	УровеньАдреснОбъекта *int       `xml:"УровеньАдреснОбъекта,omitempty"`
	Страна               *Страна    `xml:"Страна,omitempty"`
	Индекс               *string    `xml:"Индекс,omitempty"`
	ОКАТО                *string    `xml:"ОКАТО,omitempty"`
	Регион               *string    `xml:"Регион,omitempty"`
	АвтономныйОкруг      *string    `xml:"АвтономныйОкруг,omitempty"`
	Район                *string    `xml:"Район,omitempty"`
	Город                *string    `xml:"Город,omitempty"`
	ВнутригородскРайон   *string    `xml:"ВнутригородскРайон,omitempty"`
	НаселПункт           *string    `xml:"НаселПункт,omitempty"`
	Улица                *string    `xml:"Улица,omitempty"`
	Дом                  *string    `xml:"Дом,omitempty"`
	Корпус               *string    `xml:"Корпус,omitempty"`
	Строение             *string    `xml:"Строение,omitempty"`
	Помещение            *string    `xml:"Помещение,omitempty"`
}

// НормАдрес is generated from an XSD element.
type НормАдрес struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// ТипАдреса is generated from an XSD element.
type ТипАдреса struct {
	Идентификатор int    `xml:"Идентификатор"`
	Наименование  string `xml:"Наименование"`
}

// Страна is generated from an XSD element.
type Страна struct {
	Наименование string  `xml:"Наименование"`
	Код          *string `xml:"Код,omitempty"`
}
