// generated by goxsd; DO NOT EDIT

package f311sfc0v512

import "time"

type (
	AnyURIXML             string
	BooleanXML            bool
	DateTimeXSD           time.Time
	DateXSD               time.Time
	DecimalXML            float64
	DurationXML           time.Duration
	Float64XML            float64
	IntXML                int
	IntegerXML            int
	LanguageXML           string
	LongIntXML            int64
	NameXML               string
	NonNegativeIntegerXML string
	NormalizedStringXML   string
	PositiveIntegerXML    uint
	ShortIntXML           int16
	StringXML             string
	TimeXSD               time.Time
	TokenXML              string
	UnsignedShortIntXML   uint16
)

// Fajl is generated from an XSD element.
type Fajl struct {
	IdFajl     StringXML  `xml:"ИдФайл,attr"`
	TipInf     StringXML  `xml:"ТипИнф,attr"`
	VersProg   StringXML  `xml:"ВерсПрог,attr"`
	TelOtpr    StringXML  `xml:"ТелОтпр,attr"`
	DolzhnOtpr StringXML  `xml:"ДолжнОтпр,attr"`
	FamOtpr    StringXML  `xml:"ФамОтпр,attr"`
	KolDok     IntegerXML `xml:"КолДок,attr"`
	VersForm   StringXML  `xml:"ВерсФорм,attr"`
	Dokument   Dokument   `xml:"Документ"`
}

// Dokument is generated from an XSD element.
type Dokument struct {
	IdDok     StringXML `xml:"ИдДок,attr"`
	KND       string    `xml:"КНД,attr"`
	KodNOB    StringXML `xml:"КодНОБ,attr"`
	NomSoob   StringXML `xml:"НомСооб,attr"`
	TipSoob   StringXML `xml:"ТипСооб,attr"`
	DolzhnPrB StringXML `xml:"ДолжнПрБ,attr"`
	FamPrB    StringXML `xml:"ФамПрБ,attr"`
	TelBanka  StringXML `xml:"ТелБанка,attr"`
	DataSoob  StringXML `xml:"ДатаСооб,attr"`
	SvBank    SvBank    `xml:"СвБанк"`
	SvNP      SvNP      `xml:"СвНП"`
	SvSchet   SvSchet   `xml:"СвСчет"`
	Sovlad    []Sovlad  `xml:"Совлад,omitempty"`
}

// SvBank is generated from an XSD element.
type SvBank struct {
	RegNom IntegerXML `xml:"РегНом,attr"`
	NomF   IntegerXML `xml:"НомФ,attr"`
	BIK    string     `xml:"БИК,attr"`
	NaimKO StringXML  `xml:"НаимКО,attr"`
	INNKO  StringXML  `xml:"ИННКО,attr"`
	KPPKO  StringXML  `xml:"КППКО,attr"`
	OGRNKO StringXML  `xml:"ОГРНКО,attr"`
}

// SvNP is generated from an XSD element.
type SvNP struct {
	KodLitsa StringXML `xml:"КодЛица,attr"`
	NPFL     NPFLTip   `xml:"НПФЛ"`
}

// NPFLTip is generated from an XSD element.
type NPFLTip struct {
	INNFL      StringXML `xml:"ИННФЛ,attr"`
	DataRozhd  StringXML `xml:"ДатаРожд,attr"`
	MestoRozhd StringXML `xml:"МестоРожд,attr"`
	KodDUL     StringXML `xml:"КодДУЛ,attr"`
	SerNomDok  StringXML `xml:"СерНомДок,attr"`
	DataDok    StringXML `xml:"ДатаДок,attr"`
	FIOFL      FIOTip    `xml:"ФИОФЛ"`
}

// FIOTip is generated from an XSD element.
type FIOTip struct {
	Familija  StringXML `xml:"Фамилия,attr"`
	Imja      StringXML `xml:"Имя,attr"`
	Otchestvo StringXML `xml:"Отчество,omitempty,attr"`
}

// SvSchet is generated from an XSD element.
type SvSchet struct {
	NomSch      StringXML  `xml:"НомСч,attr"`
	DataOtkrSch StringXML  `xml:"ДатаОткрСч,attr"`
	KodSch      StringXML  `xml:"КодСч,attr"`
	ValSch      StringXML  `xml:"ВалСч,attr"`
	NaznSch     StringXML  `xml:"НазнСч,attr"`
	KolSovl     IntegerXML `xml:"КолСовл,attr"`
	Otkryt      *Otkryt    `xml:"Открыт,omitempty"`
	Zakryt      *Zakryt    `xml:"Закрыт,omitempty"`
}

// Otkryt is generated from an XSD element.
type Otkryt struct {
	KodSostSch  StringXML `xml:"КодСостСч,attr"`
	NomerDog    StringXML `xml:"НомерДог,attr"`
	KodSostDog  StringXML `xml:"КодСостДог,attr"`
	DataZaklDog StringXML `xml:"ДатаЗаклДог,attr"`
}

// Zakryt is generated from an XSD element.
type Zakryt struct {
	KodSostSch  StringXML `xml:"КодСостСч,attr"`
	DataZakrSch StringXML `xml:"ДатаЗакрСч,attr"`
	NomerDog    StringXML `xml:"НомерДог,omitempty,attr"`
	KodSostDog  StringXML `xml:"КодСостДог,attr"`
	DataRastDog StringXML `xml:"ДатаРастДог,attr"`
}

// Sovlad is generated from an XSD element.
type Sovlad struct {
	KodLitsa StringXML `xml:"КодЛица,attr"`
}
